### ISSUE TITLE
Django 2.1 update causing for error, renderer()

### ISSUE THREAD

**Issue by Fhall21** [jazzband/django-floppyforms#201]
Hey there!
I saw your work and would love to be able to use it, yet it seems like the new Django update (2.1) has caused for a new parameter to be needed, at least I think that's it?
The error I am getting is: get_context() got an unexpected keyword argument 'renderer'
View this page for a possible solution:
https://stackoverflow.com/questions/52039654/django-typeerror-render-got-an-unexpected-keyword-argument-renderer

**Comment by igorkurochka** [comment]
+1 same here
and it looks like this is really old issue https://github.com/gregmuellegger/django-floppyforms/issues/192
is there any chance this would be fixed anytime soon?

**Comment by igorkurochka** [comment]
there is PR created by @rtpg and it works like a charm https://github.com/gregmuellegger/django-floppyforms/pull/203 
I'm going to use their version until it gets merged here

**Comment by rtpg** [comment]
The latest release (`1.8.0`) should support 2.1 cleanly. Closing this for now

**Comment by igorkurochka** [comment]
confirm that it works well for Django 2.2.6 too.
thanks guys!
