### ISSUE TITLE
Django 3 'six' incompatability

### ISSUE THREAD

**Issue by catastrophix** [jazzband/django-floppyforms#214]
Upgrade to Django 3 results in "ImportError: cannot import name 'six'" error.

Six has been deprecated in Django 3. See [this thread on stackoverflow](https://stackoverflow.com/questions/59193514/importerror-cannot-import-name-six-from-django-utils)

**Comment by javiermatos** [comment]
I have dome some changes to try to fix this. They are in #219.

**Comment by rtpg** [comment]
@catastrophix this is fixed in the latest release
