### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by matmunn** [jazzband/django-floppyforms#215]
There seems to be minimal activity on this project and it doesn't work on Django 2.2

**Comment by javiermatos** [comment]
I have submitted a PR #219 to have Django 3.0 compatibility. I think it should work with Django 2.2 too. I am already using it in production.

**Comment by matmunn** [comment]
Given that this is the first comment on this issue which has been open for 4 months, I'd say it's dead.

I ended up removing floppyforms and using functionality which has since been built into core Django to solve the issues.

**Comment by dennisvd** [comment]
According to PYPI the last supported Django version is 2.1. So yes it seems that there isn't enough interest. I'm currently removing floppyforms in a project I'm working on.

**Comment by rtpg** [comment]
Ah, somehow I missed this thread.

This project is effectively in maintenance mode for the most part. The core functionality of floppyforms is now present within Django directly, though I think auxiliary stuff around GeoDjango might not. My main focus is mainting compatibility with later versions of Django

**Comment by rtpg** [comment]
Let's say the project is _not meant to be dead_, but I have to be paying attention to things in this repo. I have set my notifications to be much louder on this repo to see this kind of stuff.

@matmunn do you have a specific issue occurring in Django 2.2? I have this running in a 2.2 production environment for a while without any noticable issues (though perhaps this isn't indicated properly in the metadata)

@dennisvd I think you were asking about this in the IRC as well, if you're hitting a specific issue please tell me and I'll see if I can look into it (blocking some maintenance time tomorrow for this project)

**Comment by matmunn** [comment]
@rtpg I can't remember anymore, it was something to do with one of the template tags. I ended up pulling floppyforms out and using the core functionality.

**Comment by rtpg** [comment]
alright, can't blame you. There's a new release out now so hopefully this will make this project be considered a bit less dead. Apologies again for the delays on all of this
